ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: "go/src/github.com/demo-apps/go-gin-app"
workspaceLocation: "go/src/github.com/demo-apps/go-gin-app"
tasks:
  - init: >
      go build -o app
    command: >
      ./app
vscode:
  extensions:
    - golang.go