ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: "go/src/github.com/takshpanchal/chess"
workspaceLocation: "go/src/github.com/takshpanchal/chess"
tasks:
  - init: >
      go build -o app
    command: >
      ./app
vscode:
  extensions:
    - golang.go